[[redirects]]
  from = "/glossary"
  to = "https://dfe-glossary.herokuapp.com/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://becoming-a-teacher.design-history.education.gov.uk/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "public"
