[[redirects]]
  from = "/glossary"
  to = "https://design.education.gov.uk/content-design/style-guide/"
  status = 301
  force = true

[[redirects]]
  from = "https://bat-design-history.netlify.app/*"
  to = "https://becoming-a-teacher.design-history.education.gov.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/school-placements/*"
  to = "/manage-school-placements/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "public"
